[package]
name = "simdjson"
version = "0.1.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"

[dependencies]
lazy_static = "1"


[features]
default = ["swar-number-parsing"]
swar-number-parsing = []