[package]
name = "simd-json"
version = "0.1.0"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2018"
exclude = [ "data/*" ]
license = "Apache-2.0/MIT"
description = "High performance JSON parser based on a port of simdjson"
repository = "https://github.com/Licenser/simdjson-rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1" }
hashbrown = { version = "0.2", features = ["serde"] }
lazy_static = "1"
page_size = "0.4"

# Thisn should be  a dev dependecy but we can't make it optional then
# simdjson-rust = { git = "https://github.com/SunDoge/simdjson-rust", optional = true }
jemallocator = { version = "0.3", optional = true }
perfcnt = { version = "0.4", optional = true }

[dev-dependencies]
proptest = "0.9.2"
serde_derive = "*"
serde_bytes = "*"
criterion = "0.2"
#criterion = { path = "../criterion.rs" }
core_affinity = "*"


[[bench]]
name = "parse"
harness = false


[features]
default = ["swar-number-parsing"]
swar-number-parsing = []
no-inline = []
bench-serde = []
hints = [] # requires nightly
perf = ["perfcnt"]


[[example]]
name = "perf"
