version: 2.1

#orbs:
#  codecov: codecov/codecov@1.0.4

jobs:
  test:
    docker:
      - image: rust:1
    steps:
      - run:
          name: Install cmake
          command: apt install -y cmake
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests (borrowed)
          command: cargo test --all
      - run:
          name: Run all tests (owned)
          command: cargo test --all --features no-borrow

workflows:
  version: 2
  workflow:
    jobs:
    - test
